### ISSUE TITLE
Download link is broken

### ISSUE THREAD

**Issue by un-certainty** [chujiezheng/ChID-Dataset#9]
Hi @chujiezheng ,

The link is broken: https://1drv.ms/f/s!Aky8v8NZbQx1qjlNdQb7Tb9vLSKc

![image](https://user-images.githubusercontent.com/102007104/209511113-a2a4a080-eb53-4faa-acdf-c918c179c715.png)

**Comment by chujiezheng** [comment]
This link seems work again

**Comment by un-certainty** [comment]
Still not working on my side :(

Could you open it in incognito mode?

**Comment by chujiezheng** [comment]
Yes, I can open it in incognito mode. Maybe clear you cache or cookies?
